---
title: "gencor_plots"
author: "Gokberk Alagoz, L&G Dept., MPI for Psycholinguistics"
date: "`r Sys.Date()`"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(corrplot)
library(reshape2)
library(dplyr)
library(tidyr)
library(tidyverse)
library(fclust)
#devtools::install_github("NightingaleHealth/ggforestplot")
library(ggforestplot)
```

```{r read_results}
# Read gencor results of rhythm vs. dyslexia, genlang and danish school grades traits
gencor_out = read.table("/data/clusterfs/lag/users/gokala/beat-dyslexiaevol/results/gencor/rhythm_gencors/extracted/all_gencors.tab", header = T)

# all_rg = data.frame(trait = as.character(),
#                     rg = as.numeric(),
#                     se = as.numeric(),
#                     p = as.numeric())
# 
# j = 1
# for (i in gencor_outs) {
#   
#   tmp_row = read.table(i, header = T)
#   all_rg[j,] = tmp_row[1, c(2, 9, 10, 12)]
#   j = j + 1
#   
# }
# 
# all_rg = all_rg[-c(9,10,11),]

# get fdr corrected pvals

gencor_out$trait_names = c("Dyslexia",
                           "Non-word Reading",
                           "Non-word Repetition",
                           "Phoneme Awareness",
                           "Non-verbal IQ",
                           "Spelling",
                           "Word Reading",
                           "Overall school performance",
                           "Language better than maths",
                           "Oral exam better than written",
                           "Danish better than English")

colnames(gencor_out) = c("T1", "T2", "Rg", "se", "p", "name")

# Add Yasmina's results
neuro_df = data.frame(T1 = c("rhythm", "rhythm"),
                      T2 = c("language_resting-state_functional_connectivity",
                             "planum_temporale_asymmetry"),
                      Rg = c(0.28, 0.10),
                      se = c(0.05, 0.05),
                      p = c(8.72e-32, 1.51e-05),
                      name = c("Language Resting-state Functional Connectivity",
                               "Planum Temporale Asymmetry"))

gencor_out = rbind(gencor_out, neuro_df)

gencor_out$fdr = p.adjust(gencor_out$p, method = "fdr")
gencor_out$fdr = as.numeric(gencor_out$fdr)

# arrange data types of each column accordingly for subsequent analysis
# and plotting
gencor_out$T1 = as.factor(gencor_out$T1)
gencor_out$T2 = as.factor(gencor_out$T2)
gencor_out$Rg = as.numeric(gencor_out$Rg)
gencor_out$se = as.numeric(gencor_out$se)
gencor_out$p = as.numeric(gencor_out$p)

################################################################################

# read external sumstat (psychiatric and UKB traits) gencor results
ext_gencor = read.table("/data/clusterfs/lag/users/gokala/beat-dyslexiaevol/results/gencor/external_sumstats/extracted/all_gencors.tab", 
                        header = T, fill = T)

# read external sumstats' phenotype and file names
ext_traitsum = read.csv2("/data/workspaces/lag/workspaces/lg-genlang/Working/23andMe/Dyslexia2/Evolution/dys_rhy_pleiotropy/resources/external_sumstats/sumstats_summary_v2.csv",
                         header = T, sep = "\t")

```

```{r plotRhythmGencors}

gencor_out$name = factor(gencor_out$name,levels=gencor_out$name)

gencor_out$sig = ifelse(gencor_out$fdr < 0.05,'#00786A', 'black')

ggplot(gencor_out,
       aes(x = name, y = Rg)) +
       geom_errorbar(aes(ymax = Rg + se,  ymin = Rg - se),
       position = position_dodge(0.9),width=0) +
       geom_point(position = position_dodge(0.9), size = 2, colour = gencor_out$sig) +
       labs(y = "Genetic Correlation (Rg)", x = "Traits") +
       coord_flip() + ylim(c(-0.5, 0.5)) +
       geom_hline(yintercept = 0, linetype="dotted", color = "red", size=0.5) +
       scale_x_discrete(limits = rev(levels(gencor_out$name))) +
       theme(plot.title = element_text(hjust = 0.5), text=element_text(size=17)) + theme_minimal()

# ggsave("/data/workspaces/lag/workspaces/lg-genlang/Working/23andMe/Dyslexia2/Evolution/dys_rhy_pleiotropy/results/gencor/rhythm_vs_dys_genlang_danish_gencor.pdf")

# Define the order of traits as you want
order = c("Dyslexia", "Word Reading", "Phoneme Awareness", "Non-word Reading", 
          "Non-word Repetition", "Spelling", "Non-verbal IQ",
          "Overall school performance", "Language better than maths",
          "Oral exam better than written", "Danish better than English",
          "Language Resting-state Functional Connectivity", "Planum Temporale Asymmetry")

# use arrange() to order the data by variable, subgroup, and study columns
gencor_out_ordered <- gencor_out %>%
  arrange(match(name, order), T1, T2, Rg, se, p, fdr)

# Plot a forestplot
p = ggforestplot::forestplot(
  df = gencor_out_ordered,
  estimate = gencor_out_ordered$Rg,
  pvalue = gencor_out_ordered$fdr,
  psignif = 0.05,
  xlab = "Genetic correlations",
  xmin = gencor_out_ordered$Rg - 1.96 * !!gencor_out_ordered$se,
  xmax = gencor_out_ordered$Rg + 1.96 * !!gencor_out_ordered$se
) + ggplot2::coord_cartesian(xlim = c(-0.5, 0.5))

#ggsave("/data/workspaces/lag/workspaces/lg-genlang/Working/23andMe/Dyslexia2/Evolution/dys_rhy_pleiotropy/results/gencor/rhythm_vs_dys_genlang_danish_gencor_v2.pdf", p,
#       width = 8, height = 5, dpi = 600)

```

```{r plotExternalGencors}

# Create a lookup table that maps each unique trait code to a unique identifier
lookup_table <- data.frame(trait_code = unique(c(ext_gencor$T1, ext_gencor$T2)),
                           trait_id = 1:length(unique(c(ext_gencor$T1, ext_gencor$T2))))

# Join the lookup table to the genetic_correlations data frame to replace trait codes with unique identifiers
ext_gencor <- merge(ext_gencor, lookup_table, by.x = "T1", by.y = "trait_code", all.x = TRUE)
ext_gencor <- merge(ext_gencor, lookup_table, by.x = "T2", by.y = "trait_code", all.x = TRUE)
colnames(ext_gencor)[6:7] <- c("T1_id", "T2_id")

# Convert the data from long to wide format
genetic_correlations_wide <- dcast(ext_gencor, T1_id ~ T2_id, value.var = "Rg")

# Remove the T1_id column to get a matrix of genetic correlations
cor_matrix <- as.matrix(genetic_correlations_wide[,-1])

# plot
pdf("/data/workspaces/lag/workspaces/lg-genlang/Working/23andMe/Dyslexia2/Evolution/dys_rhy_pleiotropy/results/gencor/all_external_traits.pdf")
corrplot(cor_matrix, is.corr = F, tl.pos='n')
dev.off()

pdf("/data/workspaces/lag/workspaces/lg-genlang/Working/23andMe/Dyslexia2/Evolution/dys_rhy_pleiotropy/results/gencor/all_external_traits_v2.pdf")
corrplot(cor_matrix, is.corr = F, type = 'lower', tl.pos = 'l', tl.cex = 0.5, order = 'hclust')
dev.off()

```

```{r filterTraits}

# Make a subset of traits that are >0.80 correlated among each other.
ext_gencor$Rg = as.numeric(ext_gencor$Rg)
ext_gencor$SE = as.numeric(ext_gencor$SE)
ext_gencor$P = as.numeric(ext_gencor$P)

# select trait pairs with Rg less than -0.8 or greater than 0.8, and exclude Rg=1.0 pairs
high_corr_pairs <- ext_gencor %>% 
  filter(Rg != 1.0 & abs(Rg) > 0.8) %>% 
  select(T1, T2)

# Get a list of all unique traits in high_corr_pairs
high_cor_list = unique(c(high_corr_pairs$T1, high_corr_pairs$T2))
# there are 46 traits that are >0.8 genetically correlated among
# each other.

high_ext_gencor = rbind(ext_gencor[grep(paste(high_cor_list, collapse = "|"), ext_gencor$T1),],
                        ext_gencor[grep(paste(high_cor_list, collapse = "|"), ext_gencor$T2),])

high_cor_data <- ext_gencor[ext_gencor$T1 %in% high_cor_list & ext_gencor$T2 %in% high_cor_list, ]

# create a correlation matrix with only the Rg values for the high correlation pairs
high_cor_matrix <- as.matrix(reshape2::dcast(high_cor_data, T1_id ~ T2_id, value.var = "Rg")[,-1])
row.names(high_cor_matrix) <- colnames(high_cor_matrix) <- high_cor_list

# HIERCAHICAL CLUSTERING TO CHOOSE REPRESENTATIVE TRAITS
# Create a distance matrix from the correlation matrix of highly
# correlated traits.
high_dist_matrix <- as.dist(1 - high_cor_matrix)

# Perform hierarchical clustering
high_hclust_results <- hclust(high_dist_matrix, method = "ward.D2")

#pdf("/data/workspaces/lag/workspaces/lg-genlang/Working/23andMe/Dyslexia2/Evolution/dys_rhy_pleiotropy/results/gencor/hclust_46topCorrelatedTraits.pdf")
plot(high_hclust_results, cex = 0.25, main = "Genetic Correlations among highly correlated traits", hang = -1)
#dev.off()

# Determine the optimal number of clusters using the elbow method
high_wss <- sapply(2:10, function(k) sum(kmeans(high_dist_matrix, centers = k)$withinss))


# Identify the elbow point using the "knee point" algorithm
high_knee <- function(x, y) {
  dx <- x - lag(x)
  dy <- y - lag(y)
  k <- which.max(dx * dy) + 1
  return(k)
}

high_num_clusters <- high_knee(2:10, high_wss)
pdf("/data/workspaces/lag/workspaces/lg-genlang/Working/23andMe/Dyslexia2/Evolution/dys_rhy_pleiotropy/results/gencor/hclust_46topCorrelatedTraits_elbowpoint.pdf")
plot(2:10, high_wss, type = "b", xlab = "Number of clusters", ylab = "Within-cluster sum of squares")
abline(v = high_num_clusters, col = "red")
dev.off()

# Cut the dendrogram at the optimal number of clusters
high_clusters <- cutree(high_hclust_results, k = high_num_clusters)

# Identify the most informative and representative traits for each cluster
high_top_traits <- sapply(1:high_num_clusters, function(x) high_ext_gencor$T1[high_clusters == x][which.max(abs(high_cor_matrix[,high_clusters == x]))])
# Hierarch. clustering identified 7 clusters and 7 traits that represent these 
# clusters using variation data of 46 traits.
#[1] "2188.gwas.imputed_v3.both_sexes"               "816.gwas.imputed_v3.both_sexes"               
#[3] "1930.gwas.imputed_v3.both_sexes"               "6138_2.gwas.imputed_v3.both_sexes"            
#[5] "4581.gwas.imputed_v3.both_sexes"               "6138_5.gwas.imputed_v3.both_sexes"            
#[7] "METAANALYSIS_PA_RT_EUR_combined_STERR_GCOFF_1"

# Take these 7 traits and add on top of the 42 traits that are not >|80| gen. correlated
# with another trait.
uncorrelated_traits = setdiff(levels(as.factor(ext_gencor$T1)), high_cor_list)

final_trait_list = c(high_top_traits, uncorrelated_traits) # finla number, 49 traits.

#write.table(final_trait_list, file = "/data/workspaces/lag/workspaces/lg-genlang/Working/23andMe/Dyslexia2/Evolution/dys_rhy_pleiotropy/results/gencor/final_selection.txt",
#            quote = F, row.names = F, col.names = F)
```

```{r plotFactorGencors}

# read gencor results between common and independent factors and 49 selected external sumstats
factor_gencors = read.table("/data/clusterfs/lag/users/gokala/beat-dyslexiaevol/results/gencor/CPM_IPM_vs_49traits/extracted/all_gencors.tab", header = T)
factor_gencors$Rg = as.numeric(factor_gencors$Rg)
factor_gencors$SE = as.numeric(factor_gencors$SE)
factor_gencors$P = as.numeric(factor_gencors$P)
factor_gencors$fdr = p.adjust(factor_gencors$P, method = "fdr")

# plot a forestplot
factor_gencor_plot = factor_gencors %>%
  ggplot(aes(x = T1, y = Rg, col = T2, group = T2)) + 
  geom_errorbar(aes(ymax = Rg + SE,  ymin = Rg - SE), position = position_dodge(0.9)) +
  geom_point(position = position_dodge(0.9), size = 2) +
  scale_color_manual(values=c("orange", "darkblue", "darkgreen")) +
  labs(y = "Genetic correlation", 
       x = "Trait") +
  coord_flip() +
  theme_classic() +
  theme(axis.text=element_text(size=4),
        axis.title=element_text(size=8,face="bold"))

# Extract the trait names
selected_traits <- factor_gencors %>% pull(T1)

# Filter the dataset for the traits above and all three factors:
df_compare_traits <-
  factor_gencors %>%
  filter(T1 %in% selected_traits) %>%
  # Set class to factor to set order of display.
  mutate(
    T2 = factor(
      T2,
      levels = c("GenomicSEM_multivarGWAS_CPM_dys_rhyimp",
                 "GenomicSEM_multivarGWAS_dys_IPM",
                 "GenomicSEM_multivarGWAS_rhyimp_IPM")
    )
  )

df_compare_traits$T1 = as.vector(df_compare_traits$T1)
df_compare_traits$T2 = as.vector(df_compare_traits$T2)
colnames(df_compare_traits) = c("name", "T2", "Rg", "se", "P", "fdr")

# Plot a forestplot
p = ggforestplot::forestplot(
  df = df_compare_traits,
  estimate = df_compare_traits$Rg,
  pvalue = df_compare_traits$fdr,
  psignif = 0.05,
  xlab = "Genetic correlations",
  colour = df_compare_traits$T2,
  xmin = df_compare_traits$Rg - 1.96 * !!df_compare_traits$se,
  xmax = df_compare_traits$Rg + 1.96 * !!df_compare_traits$se
) +
  scale_color_manual(values=c("orange", "darkblue", "darkgreen")) +
  theme(axis.text=element_text(size=4),
        axis.title=element_text(size=8,face="bold"),
        legend.text = element_text(size = 4),
        legend.title = element_text(size = 4))

#ggsave("/data/workspaces/lag/workspaces/lg-genlang/Working/23andMe/Dyslexia2/Evolution/dys_rhy_pleiotropy/results/gencor/factors_vs_selected49traits.pdf", p,
#       width = 8, height = 15, dpi = 600)

#######################################################
# replace trait codes with decent trait names for the publication figure
trait_desc = ext_traitsum[,c(1,2,5)]

# remove ".sumstats.gz" from file names to match what we have in munged file names
trait_desc$GWAS_summary_statistics_file = str_replace(trait_desc$GWAS_summary_statistics_file,
                                                      pattern = ".sumstats.gz", replacement = "")
colnames(trait_desc) = c("Category", "Measured_phenotype", "name")

# merge trait names and genetic correlations, rename colnames
# cuz forestplot needs a specific colname: name
merged_df = merge(df_compare_traits, trait_desc, by = "name")
merged_df = merged_df[,-1]
colnames(merged_df) = c("T2", "Rg", "se", "P", "fdr", "group", "name")

# replace factor file names with nice names
merged_df[merged_df$T2=="GenomicSEM_multivarGWAS_CPM_dys_rhyimp",]$T2 = "Common Factor"
merged_df[merged_df$T2=="GenomicSEM_multivarGWAS_dys_IPM",]$T2 = "Dyslexia Independent Factor"
merged_df[merged_df$T2=="GenomicSEM_multivarGWAS_rhyimp_IPM",]$T2 = "Rhythm Impairment Independent Factor"

# Plot a forestplot with trait categories
p2 = ggforestplot::forestplot(
  df = merged_df,
  estimate = merged_df$Rg,
  pvalue = merged_df$fdr,
  psignif = 0.05,
  xlab = "Genetic correlations",
  colour = merged_df$T2,
  xmin = merged_df$Rg - 1.96 * !!merged_df$se,
  xmax = merged_df$Rg + 1.96 * !!merged_df$se
) +
  ggforce::facet_col(
    facets = ~group,
    scales = "free_y",
    space = "free"
) +
  scale_color_manual(values=c("orange", "darkblue", "darkgreen")) +
  theme(legend.position = "bottom") +
  labs(colour = "Factors")  #+
  #theme(axis.text=element_text(size=4),
  #      axis.title=element_text(size=8,face="bold"),
  #      legend.text = element_text(size = 4),
  #      legend.title = element_text(size = 4))

#ggsave("/data/workspaces/lag/workspaces/lg-genlang/Working/23andMe/Dyslexia2/Evolution/dys_rhy_pleiotropy/results/gencor/factors_vs_selected49traits_v2.pdf", p2,
#       width = 10, height = 15, dpi = 600)

# Plot a forestplot
p3 = ggforestplot::forestplot(
  df = merged_df,
  estimate = merged_df$Rg,
  pvalue = merged_df$fdr,
  psignif = 0.05,
  xlab = "Genetic correlations",
  colour = merged_df$T2,
  xmin = merged_df$Rg - 1.96 * !!merged_df$se,
  xmax = merged_df$Rg + 1.96 * !!merged_df$se
) +
  scale_color_manual(values=c("orange", "darkblue", "darkgreen")) +
  theme(legend.position =  "bottom") #+
  #theme(axis.text=element_text(size=4),
  #      axis.title=element_text(size=8,face="bold"),
  #      legend.text = element_text(size = 4),
  #      legend.title = element_text(size = 4))

#ggsave("/data/workspaces/lag/workspaces/lg-genlang/Working/23andMe/Dyslexia2/Evolution/dys_rhy_pleiotropy/results/gencor/factors_vs_selected49traits_v3.pdf", p3,
#       width = 10, height = 15, dpi = 600)

###########################################
# Plot a forestplot for publicationn
# merge education and cognitive traits categories
# add pain into Physical health and exercise
merged_df[merged_df$group=="Education",]$group = "Education & Cognitive"
merged_df[merged_df$group=="Cognitive",]$group = "Education & Cognitive"
merged_df[merged_df$group=="Pain",]$group = "Physical health and exercise"
merged_df[merged_df$group=="Reading and language (GenLang)",]$group = "Education & Cognitive"
merged_df[merged_df$group=="Education & Cognitive",]$group = "Reading, Education & Cognition"

p4 = ggforestplot::forestplot(
  df = merged_df,
  estimate = merged_df$Rg,
  pvalue = merged_df$fdr,
  psignif = 0.05,
  xlab = "Genetic correlations",
  colour = merged_df$T2,
  xmin = merged_df$Rg - 1.96 * !!merged_df$se,
  xmax = merged_df$Rg + 1.96 * !!merged_df$se
) +
  ggforce::facet_col(
    facets = ~group,
    scales = "free_y",
    space = "free"
) +
  scale_color_manual(values=c("orange", "darkblue", "darkgreen")) +
  theme(legend.position = "bottom") +
  labs(colour = "Factors")

#ggsave("/data/workspaces/lag/workspaces/lg-genlang/Working/23andMe/Dyslexia2/Evolution/dys_rhy_pleiotropy/results/gencor/factors_vs_selected49traits_v4.pdf", p4,
#       width = 10, height = 15, dpi = 600)

```
```{r}
# read gencor results between common and independent factors and 49 selected external sumstats
metabrainres = read.table("/data/workspaces/lag/workspaces/lg-sulcal-morphology/working_data/overlap/metabrain_results.txt", header = T)
metabrainres$Beta = as.numeric(metabrainres$Beta)
metabrainres$Standard_error = as.numeric(metabrainres$Standard_error)
metabrainres$P.value = as.numeric(metabrainres$P.value)
metabrainres$fdr = p.adjust(metabrainres$P.value, method = "fdr")
colnames(metabrainres)[17] = "se"
colnames(metabrainres)[6] = "name"
metabrainres$name = as.factor(metabrainres$name)
# plot a forestplotggforestplot::forestplot
eqtl_plot = ggforestplot::forestplot(
  df = metabrainres,
  estimate = metabrainres$Beta,
  pvalue = metabrainres$fdr,
  psignif = 0.05,
  xlab = "Beta",
  xmin = metabrainres$Beta - 1.96 * !!metabrainres$se,
  xmax = metabrainres$Beta + 1.96 * !!metabrainres$se
)
#write.table(metabrainres,
#            "/data/workspaces/lag/workspaces/lg-sulcal-morphology/working_data/overlap/metabrain_results.tab",
#            quote=F, row.names=F)
#ggsave("/data/workspaces/lag/workspaces/lg-sulcal-morphology/working_data/overlap/metabrain_plot.pdf", eqtl_plot,
#       width = 10, height = 5, dpi = 600)
```

